package uk.ac.liv.comp201;

public enum ResponseCode {
	CARD_NOT_FOUND,
	CARD_STATUS_BAD,
	BAD_FIRE_CODE,
	BAD_BURGLARY_CODE,
	OK,
	INVALID_FIRE_CODE,
	INVALID_BURGLARY_CODE,
	INVALID_CARD_ID_LENGTH,
	INVALID_CARD_ID,
	CARD_LOCKED_FIRE,
	CARD_LOCKED_BURGLAR_ALARM,
	CARD_LOCKED,
	INVALID_CARD
}
